# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-19 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_oil', models.CharField(max_length=250)),
                ('in_date', models.DateTimeField(verbose_name='товар получен')),
                ('added_time', models.TimeField(auto_now=True)),
                ('comments', models.TextField()),
            ],
        ),
    ]
