# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-15 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateTimeField(verbose_name='Товар получен')),
                ('name', models.CharField(max_length=250)),
                ('supplier', models.CharField(max_length=250)),
                ('consumer', models.CharField(max_length=250)),
                ('id_1C', models.CharField(max_length=250)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
