# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Код 1С')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='consumer',
            field=models.CharField(max_length=250, verbose_name='кому'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_1C',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Code', verbose_name='идентификатор партии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='income_date',
            field=models.DateTimeField(verbose_name='товар получен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='наименование продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(max_length=250, verbose_name='от кого'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(verbose_name='вес'),
        ),
    ]
