# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-25 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160715_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Код 1С'},
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'Название склада'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Название организации'},
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='c_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductName', verbose_name='наименование продукта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='s_name',
            field=models.CharField(max_length=250),
        ),
    ]
